### ISSUE TITLE
Github actions - npm install

### ISSUE THREAD

**Issue by MuzzaG** [COS301-SE-2023/Proper-Property#134]
The npm install --no-package-lock on the GitHub actions of development_v2 is failing with the same error I had on friday. Can you change the same file you did for me to try fix it.

**Comment by slaaiblaar** [comment]
Pretty sure someone who failed COS 212 would be able to write a better dependency resolution algorithm than the one used by npm-- that is if they even use one at all because at this point in time it seems like it just eeny-meeny-miny-mo's a package version and rolls with it.
